version: 2.1
orbs:
  cypress: cypress-io/cypress@3

jobs:
  run:
    docker:
      - image: cypress/base:12
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Start application
          command: npm run start
      - cypress/run

workflows:
  version: 2
  build:
    jobs:
      - run
    